import Vue from "vue";
import {
  Button,
  Cell,
  CellGroup,
  Icon,
  Image,
  Row,
  Col,
  Popup,
  Checkbox,
  CheckboxGroup,
  DatetimePicker,
  Field,
  NumberKeyboard,
  Picker,
  Radio,
  RadioGroup,
  Search,
  Stepper,
  Switch,
  SwitchCell,
  Uploader,
  ActionSheet,
  Dialog,
  DropdownMenu,
  DropdownItem,
  Loading,
  Notify,
  PullRefresh,
  SwipeCell,
  Toast,
  Collapse,
  CollapseItem,
  Divider,
  ImagePreview,
  Lazyload,
  List,
  Panel,
  Skeleton,
  Sticky,
  Swipe,
  SwipeItem,
  Tag,
  Grid,
  GridItem,
  NavBar,
  Sidebar,
  SidebarItem,
  Tab,
  Tabs,
  Tabbar,
  TabbarItem,
  TreeSelect,
  Area,
  Card,
  CouponCell,
  CouponList
} from "vant";

Vue.use(Button);
Vue.use(Cell).use(CellGroup);
Vue.use(Icon);
Vue.use(Image);
Vue.use(Row).use(Col);
Vue.use(Popup);
Vue.use(Checkbox).use(CheckboxGroup);
Vue.use(DatetimePicker);
Vue.use(Field);
Vue.use(NumberKeyboard);
Vue.use(Picker);
Vue.use(Radio).use(RadioGroup);
Vue.use(Search);
Vue.use(Stepper);
Vue.use(Switch).use(SwitchCell);
Vue.use(Uploader);
Vue.use(ActionSheet);
Vue.use(Dialog);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Loading);
Vue.use(Notify);
Vue.use(PullRefresh);
Vue.use(SwipeCell);
Vue.use(Toast);
Vue.use(Collapse).use(CollapseItem);
Vue.use(Divider);
Vue.use(ImagePreview);
Vue.use(Lazyload);
Vue.use(List);
Vue.use(Panel);
Vue.use(Skeleton);
Vue.use(Sticky);
Vue.use(Swipe).use(SwipeItem);
Vue.use(Tag);
Vue.use(Grid).use(GridItem);
Vue.use(NavBar);
Vue.use(Sidebar).use(SidebarItem);
Vue.use(Tab).use(Tabs);
Vue.use(Tabbar).use(TabbarItem);
Vue.use(TreeSelect);
Vue.use(Area);
Vue.use(Card);
Vue.use(CouponCell);
Vue.use(CouponList);
